const CONNECTION_STATUS = Object.freeze(["ONLINE", "DELAYED", "DEGRADED", "OFFLINE", "NO_DATA"]);
const ROBOT_STATUS = Object.freeze(["HEALTHY", "WARNING", "OFFLINE", "LOW_BATTERY", "BLOCKED", "NO_DATA"]);
const OPERATIONAL_MODE = Object.freeze(["ACTIVE_SAMPLING", "PATROL", "NAVIGATING", "CHARGING", "IDLE", "ERROR", "MANUAL_OVERRIDE"]);
const NAVIGATION_STATUS = Object.freeze(["ROUTE_NOT_ASSIGNED", "ROUTE_READY", "NAVIGATING", "PAUSED_FOR_INTERACTION", "BLOCKED", "REROUTING", "DOCKING", "DOCKED", "COMPLETED", "STOPPED"]);
const SAFETY_STATUS = Object.freeze(["CLEAR", "CAUTION", "OBSTACLE_NEAR", "BLOCKED_PATH", "EMERGENCY_STOP", "SENSOR_FAULT"]);
const BATTERY_STATUS = Object.freeze(["NORMAL", "LOW", "CRITICAL", "CHARGING", "CHARGING_FAILED", "UNKNOWN"]);
const DATA_QUALITY_STATUS = Object.freeze(["OK", "PARTIAL", "STALE", "INVALID", "NO_DATA"]);
const SEVERITY = Object.freeze(["INFO", "WARNING", "CRITICAL", "BLOCKER"]);
const ALERT_STATUS = Object.freeze(["OPEN", "ACKNOWLEDGED", "MITIGATING", "RESOLVED", "SUPPRESSED"]);
const TICKET_STATUS = Object.freeze(["NEW", "ASSIGNED", "RESOLVED", "REJECTED", "QUARANTINED"]);
const ADAPTER_STATUS = Object.freeze(["HEALTHY", "DEGRADED", "OFFLINE"]);

const EVENT_TYPE = Object.freeze([
  "ROBOT_ONLINE", "ROBOT_OFFLINE", "HEARTBEAT_RECEIVED", "HEARTBEAT_MISSED", "DATA_DEGRADED", "NO_DATA_RECEIVED",
  "LOW_BATTERY", "CRITICAL_BATTERY", "CHARGING_STARTED", "CHARGING_COMPLETED", "CHARGING_FAILED",
  "NAVIGATION_STARTED", "NAVIGATION_COMPLETED", "NAVIGATION_BLOCKED", "REROUTE_STARTED", "REROUTE_FAILED", "ZONE_ENTERED", "ROUTE_DEVIATION",
  "CUSTOMER_DETECTED", "CUSTOMER_INVITED", "SAMPLE_ACCEPTED", "CUSTOMER_IGNORED", "FAQ_ANSWERED", "PC_HANDOVER",
  "OBSTACLE_DETECTED", "SAFETY_STOP", "EMERGENCY_STOP", "SENSOR_FAULT", "MANUAL_OVERRIDE_STARTED", "MANUAL_OVERRIDE_ENDED"
]);

module.exports = {
  CONNECTION_STATUS,
  ROBOT_STATUS,
  OPERATIONAL_MODE,
  NAVIGATION_STATUS,
  SAFETY_STATUS,
  BATTERY_STATUS,
  DATA_QUALITY_STATUS,
  SEVERITY,
  ALERT_STATUS,
  TICKET_STATUS,
  ADAPTER_STATUS,
  EVENT_TYPE
};
